export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ACCOUNTS_ERROR = "ACCOUNTS_ERROR";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const CREATE_BAK_ACCOUNT = "CREATE_BAK_ACCOUNT";
export const SET_PRIMARY = "SET_PRIMARY";
export const CREATE_USER_PROFILE = "CREATE_USER_PROFILE";
export const CREATE_USER_PROFILE_ERROR = "CREATE_USER_PROFILE_ERROR";
